In [3]:
import pandas as pd

In [4]:
subject = ["Maths", "Science", "English" , "Social Science"]
data = [90, 100, 90, 50]
pd.Series(data, index=subject)

Maths              90
Science           100
English            90
Social Science     50
dtype: int64

In [8]:
data = {
            "maths": 50,
            "english": 100,
            "physics": 50,
            "chemistry": 89,
       }
pd.Series(data)

maths         50
english      100
physics       50
chemistry     89
dtype: int64

In [42]:
subjects = ["maths", "english", "physics", "chemistry"]
series = pd.Series(data)
series

maths         50
english      100
physics       50
chemistry     89
dtype: int64

In [13]:
series.isnull().sum()

1

In [14]:
series.notnull()

maths         True
english       True
physics       True
chemistry     True
islamiyat    False
dtype: bool

In [15]:
series[series < 90]

maths        50.0
physics      50.0
chemistry    89.0
dtype: float64

In [25]:
letters = pd.Series(['a', 'c', 'e', 'b', 'a'])
letters.sort_values(ascending=True) # Also default option

0    a
4    a
3    b
1    c
2    e
dtype: object

In [26]:
letters.sort_values(ascending=False)

2    e
1    c
3    b
0    a
4    a
dtype: object

In [36]:
Subject = ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art']
Marks = [45, 65, 78, 65, 80, 78]
CGPA = [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]
pd.DataFrame([Subject,Marks,CGPA], index = ['Subject','Marks','CGPA']).T

    Subject Marks CGPA
0     Maths    45  2.5
1   History    65  3.0
2   Science    78  3.5
3   English    65  2.0
4  Georaphy    80  4.0
5       Art    78  4.0

In [53]:
letters = pd.Series(['a', 'c', 'e', 'b'])
subjects = pd.Series(["maths", "english", "physics", "chemistry"])
pd.DataFrame([subjects, letters], index = ["Hello", "Bye"]).T

       Hello Bye
0      maths   a
1    english   c
2    physics   e
3  chemistry   b